[project]
name = "template"
version = "0.1.0"
description = "A general Python project template."
readme = "README.md"
authors = [{ name = "Will Rice", email = "wrice20@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
  "pre-commit>=4.6.2",
  "pydocstyle>=6.3.0",
  "pytest>=9.1.1",
  "python-dotenv>=1.2.3",
  "ruff>=0.16.8",
  "ty>=0.0.83",
]

[build-system]
requires = ["uv_build>=0.12.18"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["template"]

[tool.ruff.lint.isort]
known-first-party = ["template"]

[tool.ruff.lint]
select = ["C", "E", "F", "I", "W", "D", "N", "B", "PTH", "ANN"]
ignore = ["D107"]
exclude = [".venv"]

[tool.ruff.lint.pydocstyle]
convention = "google"
